package caution

import (
	"bytes"
	"compress/gzip"
	_ "embed"
	"io"
	"net/http"
	"strings"
	"sync"
)

// The prebuilt terminal, generated by cmd/bundle and committed so the SDK
// needs no build step. Refresh with `go run ./cmd/bundle` after client changes.
//
//go:embed embedded/app.js
var embeddedClient []byte

// The text engine: the native terminal's shaper and atlas rasterizer compiled
// to WebAssembly (cmd/shaperwasm), so the browser terminal renders text with
// the same code and the same embedded fonts as the native one
//
//go:embed embedded/shaper.wasm.gz
var embeddedShaperGz []byte

// The identity-encoding fallback for clients without gzip support, inflated
// on first request and cached
var shaperRaw struct {
	once  sync.Once
	bytes []byte
}

// The host page served at /.
const hostPage = `<!doctype html>
<html>
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>caution</title>
    <style>
      html, body { margin: 0; height: 100%; overflow: hidden; background: #16181d; }
      canvas { display: block; width: 100vw; height: 100vh; }
    </style>
  </head>
  <body>
    <canvas id="root"></canvas>
    <script type="module" src="/app.js"></script>
  </body>
</html>
`

// ServeAssets serves a directory of static files (images, downloads) under
// prefix. e.g. ServeAssets("/assets/", "./assets") makes ./assets/logo.png
// available to Image("/assets/logo.png").
func ServeAssets(prefix, dir string) {
	http.Handle(prefix, http.StripPrefix(prefix, http.FileServer(http.Dir(dir))))
}

// ServeClient registers "/" (the generated host page), "/app.js" (the
// terminal) and "/shaper.wasm"
func ServeClient() {
	ServeHostPage()
	http.HandleFunc("/app.js", func(w http.ResponseWriter, _ *http.Request) {
		w.Header().Set("Content-Type", "text/javascript; charset=utf-8")
		_, _ = w.Write(embeddedClient)
	})
	ServeShaperWasm()
}

// ServeShaperWasm registers "/shaper.wasm" (the shared text engine). Split out
// so caution/dev can pair the embedded engine with a source-fresh app.js.
func ServeShaperWasm() {
	http.HandleFunc("/shaper.wasm", shaperWasmHandler)
}

func shaperWasmHandler(w http.ResponseWriter, r *http.Request) {
	w.Header().Set("Content-Type", "application/wasm")
	w.Header().Set("Cache-Control", "max-age=3600")
	w.Header().Set("Vary", "Accept-Encoding")
	if strings.Contains(r.Header.Get("Accept-Encoding"), "gzip") {
		w.Header().Set("Content-Encoding", "gzip")
		_, _ = w.Write(embeddedShaperGz)
		return
	}
	shaperRaw.once.Do(func() {
		zr, err := gzip.NewReader(bytes.NewReader(embeddedShaperGz))
		if err != nil {
			return
		}
		if raw, err := io.ReadAll(zr); err == nil {
			shaperRaw.bytes = raw
		}
	})
	if shaperRaw.bytes == nil {
		http.Error(w, "caution: embedded shaper.wasm.gz is corrupt", http.StatusInternalServerError)
		return
	}
	_, _ = w.Write(shaperRaw.bytes)
}

// ServeHostPage registers "/" (the generated host page) alone, leaving
// "/app.js" to the caller. ServeClient pairs it with the embedded terminal;
// caution/dev pairs it with one bundled fresh from TypeScript source.
func ServeHostPage() {
	http.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
		if r.URL.Path != "/" {
			http.NotFound(w, r)
			return
		}
		w.Header().Set("Content-Type", "text/html; charset=utf-8")
		_, _ = w.Write([]byte(hostPage))
	})
}
